### ISSUE TITLE
Doubt about publish and subscribe

### ISSUE THREAD

**Issue by javierseixas** [fmvilas/asyncapi-examples#1]
Hola! I'm new to asyncapi, and I have a doubt about channel specification.

In the [signup example](https://github.com/fmvilas/asyncapi-examples/tree/master/internal/signup), the README says that *MetricsService* and *EmailService* are subscribe to `user.signedup` event. My doubt came when in the specification [signup-email.yml](https://github.com/fmvilas/asyncapi-examples/blob/master/internal/signup/signup-email.yml), it says:

```yaml
channels:
  /user/signedup:
    publish:
      message:
        $ref: 'signup.yml#/components/messages/userSignedUp
```

Notice the `publish` attribute. Same thing in the [signup-metrics.yml](https://github.com/fmvilas/asyncapi-examples/blob/master/internal/signup/signup-metrics.yml)

I would suppose it should be `subscribe`, since as the README says, the service is subscribing to the event `user/signedup`. It sounds more intuitive to me, at least.

Hope someone can clarify my doubts. Thanks!
